AWSTemplateFormatVersion: '2010-09-09'
Description: VPC & subnet create

Parameters:
  # プロジェクト名
  ProjectId:
    Description: Project name id.
    Type: String
    MinLength: 8
    MaxLength: 24 
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: must specify Project id.
  # DB初期PW
  DBPassword:
    Default: root1234
    NoEcho: true
    Description: The database admin account password
    Type: String
    MinLength: 8

  VPCID:
    Type: String
    Default: vpc-stack-test-001-VPCID

  DbSubnet:
    Type: String
    Default: vpc-stack-test-001-DbSubnet

Resources:
  SecurityGroupRDS:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: 'RDS Security Group'
      VpcId: { "Fn::ImportValue" : { "Ref" : "VPCID" } }
      Tags:
        - Key: 'Name'
          Value: 'SecurityGroupForRds'
      SecurityGroupIngress:
        IpProtocol: tcp
        FromPort: '3306'
        ToPort: '3306'
        CidrIp: 10.0.1.0/24

  DbInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: mysql
      AllocatedStorage: 5
      MasterUsername: root
      DBInstanceClass: db.t2.micro
      DBSubnetGroupName: { "Fn::ImportValue" : { "Ref" : "DbSubnet" } }
      VPCSecurityGroups:
      - !Ref SecurityGroupRDS
      MasterUserPassword: { "Fn::Join" : [ "", [ { "Ref": "DBPassword" }, "!Z3" ] ] }
